---
version: 2
jobs:
  test:
    docker:
      - image: circleci/ruby:latest
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: bundle install
      - run:
          name: Rubocop
          command: bundle exec rake rubocop
      - run:
          name: Inspec Validation
          command: bundle exec rake validate
workflows:
  version: 2
  test:
    jobs:
      - test
